// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChainUIClient is the client API for ChainUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainUIClient interface {
	// ListEngineSpecs returns a list of Chain Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChainUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type chainUIClient struct {
	cc grpc.ClientConnInterface
}

func NewChainUIClient(cc grpc.ClientConnInterface) ChainUIClient {
	return &chainUIClient{cc}
}

func (c *chainUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChainUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChainUI_ServiceDesc.Streams[0], "/v1.ChainUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &chainUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChainUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type chainUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *chainUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chainUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ChainUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainUIServer is the server API for ChainUI service.
// All implementations must embed UnimplementedChainUIServer
// for forward compatibility
type ChainUIServer interface {
	// ListEngineSpecs returns a list of Chain Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ChainUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedChainUIServer()
}

// UnimplementedChainUIServer must be embedded to have forward compatible implementations.
type UnimplementedChainUIServer struct {
}

func (UnimplementedChainUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ChainUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedChainUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedChainUIServer) mustEmbedUnimplementedChainUIServer() {}

// UnsafeChainUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainUIServer will
// result in compilation errors.
type UnsafeChainUIServer interface {
	mustEmbedUnimplementedChainUIServer()
}

func RegisterChainUIServer(s grpc.ServiceRegistrar, srv ChainUIServer) {
	s.RegisterService(&ChainUI_ServiceDesc, srv)
}

func _ChainUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainUIServer).ListEngineSpecs(m, &chainUIListEngineSpecsServer{stream})
}

type ChainUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type chainUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *chainUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChainUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChainUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainUI_ServiceDesc is the grpc.ServiceDesc for ChainUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChainUI",
	HandlerType: (*ChainUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ChainUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ChainUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chain-ui.proto",
}
